packages:
  - .

overrides:
  esbuild: '>=0.28.1'
  cookie: '>=1.0.0 <2'
  fast-xml-parser: '>=5.3.6'
  rollup: '>=4.59.0'
  cross-spawn: '>=7.0.5'
  glob: '>=10.5.0'
  minimatch: '>=10.2.3'
  tar: '>=7.5.11'
